title: Amar Menezes

description: >- # this means to ignore newlines until "baseurl:"
  Archive of some of my security research.
baseurl: "" 
url: "https://amarekano.github.io"
twitter_username: amarekano
github_username:  amarekano

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed