title: blog de amarekano

description: >- # this means to ignore newlines until "baseurl:"
  My ramblings on iOS and Android vulnerability research.
baseurl: "" 
url: "https://amarekano.github.io"
twitter_username: amarekano
github_username:  amarekano

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed